services:
  frontend:
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
    ports:
      - 3000:3000
    networks:
      - app_network
    environment:
      - NEXT_WEBPACK_USEPOLLING=1
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    ports:
      - 5000:5000
    volumes:
      - backend-uploads:/uploads
    networks:
      - app_network
    environment:
      - DB_URL=mongodb://devuser:devpassword@eavesdrop-mongo-1:27017/
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    volumes:
      - mongodb-data:/data/db
      - ./db/mongo-init-scripts:/docker-entrypoint-initdb.d
    networks:
      - app_network
    environment:
      MONGO_INITDB_ROOT_USERNAME: devuser
      MONGO_INITDB_ROOT_PASSWORD: devpassword

networks:
  app_network:
    external: true

volumes:
  mongodb-data:
  backend-uploads: