services:
  frontend:
    build:
      context: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - app_network
    environment:
      - NEXT_WEBPACK_USEPOLLING=1
  backend:
    build:
      context: ./backend
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - app_network
    environment:
      - CHOKIDAR_USEPOLLING=1
      - DB_URL=mongodb://devuser:devpassword@eavesdrop-mongo-1:27017/
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    volumes:
      - /db:/data/db
    networks:
      - app_network
    environment:
      MONGO_INITDB_ROOT_USERNAME: devuser
      MONGO_INITDB_ROOT_PASSWORD: devpassword
  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    networks:
      - app_network
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: devuser
      ME_CONFIG_MONGODB_ADMINPASSWORD: devpassword
      ME_CONFIG_MONGODB_URL: mongodb://devuser:devpassword@eavesdrop-mongo-1:27017/
    depends_on:
      - mongo

networks:
  app_network:
    driver: bridge