services:
  frontend:
    build:
      context: ./apps/frontend
    ports:
      - 3000:3000
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - app_network
    environment:
      - NEXT_WEBPACK_USEPOLLING=1

  backend:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    ports:
      - 5000:5000
    volumes:
      - backend-uploads:/uploads
    networks:
      - app_network
    environment:
      - DB_URL=mongodb://devuser:devpassword@eavesdrop-mongo-1:27017/
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    volumes:
      - mongodb-data:/data/db
      - ./db/mongo-init-scripts:/docker-entrypoint-initdb.d
    networks:
      - app_network
    environment:
      MONGO_INITDB_ROOT_USERNAME: devuser
      MONGO_INITDB_ROOT_PASSWORD: devpassword

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    networks:
      - app_network
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: devuser
      ME_CONFIG_MONGODB_ADMINPASSWORD: devpassword
      ME_CONFIG_MONGODB_URL: mongodb://devuser:devpassword@eavesdrop-mongo-1:27017/
    depends_on:
      - mongo

networks:
  app_network:
    driver: bridge

volumes:
  mongodb-data:
  backend-uploads: