apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend # select the users pod and expose
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-app
          image: us-west1-docker.pkg.dev/deft-crawler-400712/eavesdrop-docker-repository/frontend:latest
          env:
            - name: BACKEND_API_BASE
              value: http://backend-service:5000/api/